# Generated by Django 5.0.7 on 2024-08-03 03:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=50, verbose_name='Ruw')),
            ],
            options={
                'verbose_name': 'Род',
                'verbose_name_plural': 'Родословие',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Дата Смерти')),
                ('photo', models.ImageField(upload_to='Family/photo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('children', models.ManyToManyField(blank=True, null=True, related_name='people_children', to='people.people', verbose_name='Дети')),
                ('genus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people_genus', to='people.genus')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_spouse', to='people.people', verbose_name='Муж/Жена')),
            ],
            options={
                'verbose_name': 'Человека ',
                'verbose_name_plural': 'Люди',
            },
        ),
    ]
